<?xml version="1.0" encoding="utf-8"?><Database Name="DB_BX" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.MF_POS" Member="MF_POS">
    <Type Name="MF_POS">
      <Column Name="OS_ID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OS_NO" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BAT_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="OS_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QT_NO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="VOH_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="VOH_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TRAD_MTH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PAY_MTH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PAY_DAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CHK_DAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAY_REM" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="SEND_MTH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SEND_WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="EST_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CUS_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="SAL_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="USE_DEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CUR_ID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="EXC_RTO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMTN_INT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMT_INT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DIS_CNT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CLS_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BACK_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="HIS_PRICE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ADR" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="REM" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PO_DEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PO_SO_NO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="SO_BY_MM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SO_OT_DD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SO_BY_DD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SO_LNG_CAS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SO_END_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SO_LST_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INV_DIS_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INV_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TAX_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RP_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OLD_INV_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AMTN_NET" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAY_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHK_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INT_DAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="USR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CHK_MAN" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CONTRACT" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="PRT_SW" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CPY_SW" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BIL_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LC_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="AMTN_DIS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CLS_MP_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CLS_REM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BIL_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="RK_CLS_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PRE_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="IS_POS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="POS_NO" Type="System.String" DbType="VarChar(14)" CanBeNull="true" />
      <Column Name="CLS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PCL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CUS_OS_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BZ_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HS_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMT_LC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="BIL_TYPE" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CNTT_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SB_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MOB_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="LOCK_MAN" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="LOCK_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ISOVERSH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DJ_NO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="FJ_NUM" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CAS_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SYS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SQ_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INV_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INV_YM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TITLE_BUY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="METH_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="AMT_INV" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TAX_INV" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="FX_WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="YH_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BYBOX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TOT_QTY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TOT_BOX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TASK_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRT_USR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="RP_NO1" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SQ_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CARD_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SEND_AREA" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="JFEND_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SG_ID" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PRT_NUM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAY_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AMTN_YJBX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMTN_BX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="ISSVS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BIL_MARK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_FX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="HAS_FX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMTN_CBAC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CBAC_CLS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INV_CHK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INV_UNI_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="INV_TITLE" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="INV_AMT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAY_B2C" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CANCEL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SG_ID1" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BIL_COMP" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="RTO_FQSK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DATEFLAG_FQSK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DATE_FQSK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QS_FQSK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CUS_NO_POS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INST_TEAM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AMTN_DS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CFM_SW" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INV_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PRT_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INV_BIL_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="INV_BIL_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OFF_OS_NO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="INV_BCODE_NO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ZHANG_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMTN_CBAC_PS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="ACT_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TT_TYPE_SET" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TT_YM_B" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ICOS_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CNT_MAN1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MODIFY_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFY_MAN" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CLS_ME_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MRK" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PRM_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CX_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CX_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CHK_LATEST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SRC_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SG_BIL_COMP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SOKP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CUS_FH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="DEP_FH" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CUS_FX" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="AMTN_HX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMTN_HX_MAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="HXJS_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_CACHE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_FULL_PAY" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="GROUP_DEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CHK_FULL_PAID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="EC_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FLG_RUSH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SEND_WAY" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TF_POS" Member="TF_POS">
    <Type Name="TF_POS">
      <Column Name="OS_ID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OS_NO" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ITM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QT_NO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="PRD_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PRD_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PRD_MARK" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="OS_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QTY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DIS_CNT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMTN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PS_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_PS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_PS_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="EST_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAK_UNIT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PAK_EXC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_NW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_WEIGHT_UNIT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PAK_GW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_MEAST" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_MEAST_UNIT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="VALID_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REM" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="AMTN_COM" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CLS_MP_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CST_STD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_QTY1" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="EST_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SEND_WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="UT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CODE_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ATTR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="QTY_RK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_RK_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="BAT_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="PRE_EST_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QTY_PO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PO_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PRE" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PRE_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PRE_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_NO" Type="System.String" DbType="VarChar(38)" CanBeNull="true" />
      <Column Name="QTY_YS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_YS_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="FREE_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BIL_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="BZ_KND" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PRICE_ID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="OTH_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TAX_RTO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMT_LC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_BACK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_TAX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SUP_PRD_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="COMPOSE_IDNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QTY_SL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_SL_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CUS_OS_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="OTH_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="OTH_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ISVIR" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="JH_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="QTY_FH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_FH_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PRD_NO_SO_RES" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="FH_NO" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="FH_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QTY_IC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_IC_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="BOX_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTY_ARK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PS_ARK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_PRE_ARK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_CK_ARK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="MAI_NO" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="SCM_USR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="SCM_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QTY_SQ" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_SQ_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_PO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="SQ_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SQ_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SQ_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTY_FRAC1" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_FRAC2" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_FRAC3" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_FRAC4" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_USE_WH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TRD_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="TRD_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TRD_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRD_NAME_SO_RES" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PICPATH" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="CHK_RTN" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MO_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MO_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="WC_NO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="MTN_TYPE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MTN_ALL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MTN_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RTN_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MTN_REM" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AMT_DIS_CNT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="OTH_ITM1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FREE_ID_DEF" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UP_STD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_AE" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="SUP_PRD_NM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DETAIL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TB_OID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SUP_PRD_MARK" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="DEF_NO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MATRIX_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CF_ID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="TT_RNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TT_TYPE_IFRS" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TT_YM_E" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QTY_IO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_IO_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="IS_SP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MRP_NOS" Type="System.String" DbType="VarChar(800)" CanBeNull="true" />
      <Column Name="OR_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KIND_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="XPM_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="XPM_NO1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="XPPRD_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XPPRD_ITM1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CLS_ME_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UP_SAL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMTN_SAL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TASK_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PRM_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="QTY_LOCK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_LOCK_CK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_LOCK_CK_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_REP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="REM_XP" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PROMO_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="FRELATION" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="RECORD_TYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ZP_BEIZSMM" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ZP_CHKVAL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KEY_ITM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="REMARK_ENG" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CUS_KH_NO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GROUP_DEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="QTY1_PRE" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_PRE_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_LOCK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_LOCK_CK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_LOCK_CK_UNSH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="MALL_TID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ISSPLIT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_XZL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UNCFM_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UNCFM_REM" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UNCFM_USR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="UNCFM_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRDT" Member="PRDT">
    <Type Name="PRDT">
      <Column Name="PRD_NO" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SNM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IDX1" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IDX2" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="UT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="UT1" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="DFU_UT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SPC" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="CCC" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="KND" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SPC_TAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PK2_UT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PK2_QTY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PK3_UT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PK3_QTY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MRK" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="SUP1" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="SUP2" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="UPR" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UBPR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CST_STD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CST_SAL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="SPC_PRD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="REM" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="PIC" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="UPR_LEVEL1" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UPR_LEVEL2" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UPR_LEVEL3" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UPR_LEVEL4" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UPR_LEVEL5" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_UNIT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PAK_EXC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_NW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_WEIGHT_UNIT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PAK_GW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_MEAST" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="PAK_MEAST_UNIT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="STOP_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PRD_NO_EXC" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NEED_DAYS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="NOUSE_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BAR_CODE" Type="System.String" DbType="VarChar(23)" CanBeNull="true" />
      <Column Name="FORMULA" Type="System.String" DbType="VarChar(210)" CanBeNull="true" />
      <Column Name="NAME_ENG" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="UT_TIME" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_BAT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UP_MAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_MIN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="INV_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CST_ADD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="RB_RATE" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_LOW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="BOM_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TIME_UNIT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="OLEFIELD" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TW_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WTUT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="UP_SAL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_NUM" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SMALLPIC" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="PRD_LEVEL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PRD_PACK" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_IN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_OUT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CODENAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CHK_TAX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UPR_TP" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="BACK_RTO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PRICEXS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TYPE_CST" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PRD_NO_SGT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="HS_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UNIT_SGT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SGT_RATE" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="VALID_DAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NEED_DD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MOB_ID" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="START_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHG_DAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ACC_NO_ORI" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_SA_IN" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_SA_CST" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CHK_PRD_MARK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_MAN" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CLS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LEN_PRD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UT_LEN" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="WIDTH_PRD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UT_WIDTH" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LEN_PRD2" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="LEN_PRD3" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CAIZ" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="USR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="SYS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SPC_ID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ABC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RTO_EP" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="ZC_TYPE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="JJ_LEN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="JJ_LEN2" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="NOT_RTN" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RTO_RTN" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ACC_PRO_CST" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RTO_CL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="SAL_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="OLD_CODE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SPC_ID1" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ML_UT" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WH_LC" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="QUOTE_UT1" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="QUOTE_UT2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="QUOTE_UT3" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PRD_POI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QTY_MIN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_DD" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="DZ_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BZ_DATA" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="RTO_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="XN_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CHK_RTN" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_MTN" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_INSTALL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MTN_LTIME" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHK_PC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_TW" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="STOP_PROD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="VIRTUAL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WEIGHT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="REM_WEB" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="B2C_HIDE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WEB_TITLE" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="WEB_DESCRIPTION" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="WEB_KEYWORDS" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CADNAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QTY_MIN1" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_MAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="TL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SA_RTO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DEPRO_NO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CC_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="RTO_PC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="RTO_SA" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="RTO_MM" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="RTO_TB" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="ML_BY_MM" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TPL_NO" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="TPL_REM" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="CHK_SA" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_SB" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_MM" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_ML" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_M2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="REM_NAME" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NAME_PY" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SPC_PY" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="QTY_LOST_FIX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="USE_PRDMARK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WC_MONTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHK_ADD_WC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MOB_ID1" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="FY_FLAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ACC_NO_FC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="WH_PJSQ" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="QTY_AD_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TB_NUMIDS" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CHK_TBWH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="QTY_ML_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_BAR" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BIL_ML" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="REM_WEB_M" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
      <Column Name="CHK_WG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CPY_SW" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="MADE_NO" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="STD_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EXP_UP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EXP_SP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LOCK_MAN" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="LOCK_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="JD_NUMIDS" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="QC_UT" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="QC_QTY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_FREE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="IDX3" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SALE_BDD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SALE_EDD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="REM_UP_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPR_LEVEL6" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="S_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VALID_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRDT1" Member="PRDT1">
    <Type Name="PRDT1">
      <Column Name="WH" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PRD_NO" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PRD_MARK" Type="System.String" DbType="VarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="QTY_INT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMT_CST" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_MAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_MIN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_LRN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_BRW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_ON_WAY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_ON_PRC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_ON_RSV" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_ON_ODR" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="LST_OTD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LST_IND" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LST_SFD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UP_INT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CST_INT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CST_STD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CST_PO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CST_SAL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_STD" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_SAL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_LRN" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY1_BRW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="UP_PO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_SA" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_RK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_ZG" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_CK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_SQ" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="REM" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="CHQC_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QTY_SW" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_WX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_WS" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_WS_KC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_QL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_Q2" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_Q2_YL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_Q3" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CST_BX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_SQR" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_SQC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_LOCK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_JH" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="SC_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LST_OTD_QC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LST_IND_QC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UP_DD" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="QTY1_LOCK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="QTY_T3" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUST" Member="CUST">
    <Type Name="CUST">
      <Column Name="CUS_NO" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDX2" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CUS_ARE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MAS_CUS" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="OBJ_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SNM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NM_ENG" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="PAY_DD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CLS_MTH" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CLS_DD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="MM_END" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CHK_DD" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UNI_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BOS_NM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CNT_JOB1" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="CNT_MAN1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CNT_JOB2" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="CNT_MAN2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ACC_MAN" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SAL" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="TEL1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TEL2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ADR1" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="ADR2" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="ADR_ENG" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="ZIP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LIM_NR" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="LIM_NC" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CRD_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INV_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ID1_TAX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ID2_TAX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CLS1" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="CLS2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="STR_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="END_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CUR" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CRD_NR_NC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="REM" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="E_MAIL" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SEND_MTH" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SEND_WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="BNK_NAME" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ID_CODE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CUS_LEVEL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INC_CHECK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="LS_RTO" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="COMPNET" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="COMP_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CAPSUM" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="BUSISUM" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="SALMS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BUSINOTE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="WORKITM" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="MAIN_PRD" Type="System.String" DbType="Text" CanBeNull="true" />
      <Column Name="CHK_CRD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="S_FLAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="INITNUM" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="NOTIFY" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="BROKER" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="VESSEL" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="LOADING_PORT" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="DIS_PORT" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="MANU_PLACE" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="EPAPER" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TRAN_REC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PSWD" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PSWD_HIT" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="PSWD_ANS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="APPLY_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BIZ_DSC" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="COUNTRY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BANK_NO" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="ACC_NO_AR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_AP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_R0" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_P0" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SO_CRD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FP_NAME" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="CHK_FAX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RTO_TAX" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_CUS_IDX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CY_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="REGIST_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CORP_ID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="M_CUST" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="SAL_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CHK_DEP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="RTO_KK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DEP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="RTO_FL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="RTO_YL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DEP1" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="USR" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CHK_INCLUDE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_IRP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_TRP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_MAN" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CLS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CHK_PAY1" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PAY_DAYS" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PAY_FLAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_PAY2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_PAY3" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMTN_MAX_PAY" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_QK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMTN_QK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="USR1" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="SYS_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RTO_DISCNT" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_IRP2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="LOGON" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WH_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="STOP_ORDER" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RTN_CTRL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DRP_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="UPR4_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="YH_WH1" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="YH_WH2" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="ACC_NO_IR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_IP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="B2C_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CARD_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UP_DD" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="PRTWEEKS_PO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SOWEEKS_PO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LANG_ID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CHK_DRP1" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_DRP2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_DRP3" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SRV_NO" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CUS_IDX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="XN_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CWORK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CHK_BARCODE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ACC_NO_ZP" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HM_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PSWD_PAY" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="AMTN_FL" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="AMTN_FLED" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="CHK_SBRTO" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DEPRO_NO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="RTO_FQSK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="DATEFLAG_FQSK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DATE_FQSK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QS_FQSK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCAL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="RULE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TEL1_CODE" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="UNI_NO2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FP_NAME2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CODE_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CHK_KD" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="WS_CUS_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AUTO_CASN_CHK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="NSR_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NAME_PY" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="BIZ_DSC1" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CUS_SRC" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_AR2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ACC_NO_AP2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VISIT_LIMIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BB_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SO_DD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MOB_ID" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="TT_TYPE_SET" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EX_TRD_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="IM_TRD_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CUS_NO_KD" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CHK_ZHANG_ID2" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="PJSQ_WH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="JD_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FP_TYPE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_CX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_MIN_XF" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BIL_MIN_XF" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CHK_TYPE_MINXF" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMTN_MIN_XF" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="REM_S" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DEP_FH" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="WH_FH" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CUS_FH" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="CHK_O2O_FX" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_MALL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="FX_LEVEL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DJ_LC" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DJ_PAY" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="DJ_SQ" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="AMTN_DJ" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="LIM_NR_TYPE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_FULL_PAY" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_CK" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="ISCUSTKEY" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SUP_LEVEL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BRD_NO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CA_NO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="CA1_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="NBRD_NO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="NCA_NO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="NCA1_NO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="INTEREST" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NSZG_FLAG" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BACC_NO" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="CHK_INDX1" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="BANK_NAME" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="S_CODE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DJ_YE" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="CHK_FL" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BILN" Member="BILN">
    <Type Name="BILN">
      <Column Name="BIL_ID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BIL_NM" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="PAT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DEL_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="XG_ID" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="SEL_DD" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="SEL_ID" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SEL_DEP" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SEL_USR" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SEL_ACC" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SEL_OTH" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BIL_ID1" Type="System.String" DbType="VarChar(17)" CanBeNull="true" />
      <Column Name="SEL_NO" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SEL_CX" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TYPE_DEP" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="LST_NO" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UP_DD" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.BILN1" Member="BILN1">
    <Type Name="BILN1">
      <Column Name="BIL_ID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PAT" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SQ" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MF_POS_Z" Member="MF_POS_Z">
    <Type Name="MF_POS_Z">
      <Column Name="OS_ID" Type="System.String" DbType="VarChar(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OS_NO" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KPXX" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SCYF" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
      <Column Name="ZK" Type="System.Decimal" DbType="Decimal(22,8)" CanBeNull="true" />
    </Type>
  </Table>
</Database>